#!/usr/bin/env python3
"""Render a living schema summary page from ``src/textgraphx/schema/ontology.json``.

The hand-written narrative lives at ``docs/wiki/40-ontology-and-schema/schema-semantics.md``.
This generator emits the *table* of labels, relationships, schema tiers, and
reasoning contracts at ``docs/wiki/40-ontology-and-schema/schema-autogen.md``.

Usage::

    python scripts/docs/generate_schema_summary.py           # write file
    python scripts/docs/generate_schema_summary.py --check   # non-zero if stale
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY_PATH = REPO_ROOT / "src" / "textgraphx" / "schema" / "ontology.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "wiki" / "40-ontology-and-schema" / "schema-autogen.md"


def _fmt_list(values: object) -> str:
    if isinstance(values, list):
        if not values:
            return "—"
        return ", ".join(f"`{v}`" for v in values)
    if isinstance(values, str):
        return f"`{values}`"
    return "—"


def build_markdown(data: dict) -> str:
    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/docs/generate_schema_summary.py — DO NOT EDIT -->")
    lines.append("<!-- last_reviewed: auto | owner: core | status: auto -->")
    lines.append("")
    lines.append("# Schema Summary (auto-generated)")
    lines.append("")
    lines.append("**Gateway** · **Wiki Home** · **Ontology & Schema** · Schema Summary")
    lines.append("")
    lines.append(
        "Living table of labels, relationships, schema tiers, and reasoning "
        "contracts, rendered from [`ontology.json`](../../../src/textgraphx/schema/ontology.json). "
        "The authoritative narrative is in [`../../schema.md`](../../schema.md) "
        "(and, once published, `schema-semantics.md` in this folder)."
    )
    lines.append("")
    lines.append("Regenerate with: `python scripts/docs/generate_schema_summary.py`.")
    lines.append("")

    # Schema tiers
    tiers = data.get("schema_tiers", {}) or {}
    if tiers:
        lines.append("## Schema tiers")
        lines.append("")
        lines.append("| Tier | Node labels | Relationship types |")
        lines.append("| --- | --- | --- |")
        for tier in sorted(tiers):
            members = tiers[tier]
            if isinstance(members, dict):
                node_labels = members.get("node_labels") or []
                rel_types = members.get("relationship_types") or []
            elif isinstance(members, list):
                node_labels = members
                rel_types = []
            else:
                node_labels = []
                rel_types = []
            lines.append(
                f"| `{tier}` | {_fmt_list(sorted(node_labels))} | "
                f"{_fmt_list(sorted(rel_types))} |"
            )
        lines.append("")

    # Node labels
    nodes = data.get("nodes", {}) or {}
    if nodes:
        lines.append(f"## Node labels ({len(nodes)})")
        lines.append("")
        lines.append("| Label | Purpose | Key properties |")
        lines.append("| --- | --- | --- |")
        for label in sorted(nodes):
            info = nodes[label] or {}
            purpose = (info.get("purpose") or "").strip().replace("|", "\\|")
            key_props = info.get("key_properties") or []
            lines.append(f"| `{label}` | {purpose or '—'} | {_fmt_list(key_props)} |")
        lines.append("")

    # Relationships
    rels = data.get("relationships", {}) or {}
    if rels:
        lines.append(f"## Relationships ({len(rels)})")
        lines.append("")
        lines.append("| Type | Description |")
        lines.append("| --- | --- |")
        for rel in sorted(rels):
            info = rels[rel]
            if isinstance(info, dict):
                description = (
                    info.get("purpose")
                    or info.get("description")
                    or ""
                ).strip()
                src = info.get("source") or info.get("from")
                tgt = info.get("target") or info.get("to")
                if (src or tgt) and not description:
                    description = f"{src or '?'} → {tgt or '?'}"
            elif isinstance(info, str):
                description = info.strip()
            else:
                description = ""
            description = description.replace("|", "\\|") or "—"
            lines.append(f"| `{rel}` | {description} |")
        lines.append("")

    # Endpoint contracts
    endpoint_contract = data.get("relation_endpoint_contract", {}) or {}
    if endpoint_contract:
        lines.append(f"## Relation endpoint contracts ({len(endpoint_contract)})")
        lines.append("")
        lines.append("| Relation | Contract keys |")
        lines.append("| --- | --- |")
        for rel in sorted(endpoint_contract):
            info = endpoint_contract[rel] or {}
            if isinstance(info, dict):
                keys = sorted(info.keys())
            else:
                keys = []
            lines.append(f"| `{rel}` | {_fmt_list(keys)} |")
        lines.append("")

    # Temporal reasoning profile
    trp = data.get("temporal_reasoning_profile", {}) or {}
    if trp:
        lines.append("## Temporal reasoning profile")
        lines.append("")
        canonical = trp.get("canonical_reltypes") or []
        contradictions = trp.get("contradiction_pairs") or []
        closure = trp.get("closure_rules") or []
        lines.append(f"- Canonical relation types: {_fmt_list(canonical)}")
        if isinstance(contradictions, list):
            lines.append(f"- Contradiction pairs: `{len(contradictions)}` defined")
        if isinstance(closure, list):
            lines.append(f"- Closure rules: `{len(closure)}` defined")
        policy = trp.get("consistency_policy")
        if policy:
            lines.append(f"- Consistency policy: `{policy}`")
        dct = trp.get("dct_anchor_policy")
        if dct:
            lines.append(f"- DCT anchor policy: `{dct}`")
        lines.append("")

    # Event attribute vocabulary
    eav = data.get("event_attribute_vocabulary", {}) or {}
    if eav:
        lines.append(f"## Event attribute vocabulary ({len(eav)})")
        lines.append("")
        lines.append("| Attribute | Allowed values |")
        lines.append("| --- | --- |")
        for attr in sorted(eav):
            info = eav[attr]
            if isinstance(info, dict):
                vals = info.get("values") or list(info.keys())
            elif isinstance(info, list):
                vals = info
            else:
                vals = []
            lines.append(f"| `{attr}` | {_fmt_list(vals)} |")
        lines.append("")

    # Deprecated relationships
    dep = data.get("deprecated_relationships", {}) or {}
    if dep:
        lines.append(f"## Deprecated relationships ({len(dep)})")
        lines.append("")
        for rel in sorted(dep):
            info = dep[rel]
            if isinstance(info, dict):
                reason = info.get("reason") or info.get("replacement") or ""
            elif isinstance(info, str):
                reason = info
            else:
                reason = ""
            lines.append(f"- `{rel}` — {reason}".rstrip(" —"))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if committed schema-autogen.md is out of date.",
    )
    args = parser.parse_args()

    data = json.loads(ONTOLOGY_PATH.read_text(encoding="utf-8"))
    generated = build_markdown(data)

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"error: {OUTPUT_PATH} is missing; run generator.", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if hashlib.sha256(current.encode()).digest() != hashlib.sha256(generated.encode()).digest():
            print(
                f"error: {OUTPUT_PATH} is stale; run "
                f"`python scripts/docs/generate_schema_summary.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
