#!/usr/bin/env python3
"""Generate a public-surface code index for the wiki.

Walks the ``src/textgraphx`` package, extracts top-level public classes and
functions from each module via ``ast``, and emits a Markdown table grouped by
module at ``docs/wiki/99-references/code-index.md``.

The output is deterministic so it can be committed and diffed by CI.

Usage::

    python scripts/docs/generate_code_index.py            # write file
    python scripts/docs/generate_code_index.py --check    # non-zero if stale
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGE_ROOT = REPO_ROOT / "src" / "textgraphx"
OUTPUT_PATH = REPO_ROOT / "docs" / "wiki" / "99-references" / "code-index.md"

SKIP_DIR_NAMES = {
    "__pycache__",
    "tests",
    "notebooks",
    "datastore",
    "fixtures",
    "tarsqi-dataset",
    "docs",
}


def iter_modules(root: Path) -> Iterable[Path]:
    for path in sorted(root.rglob("*.py")):
        rel = path.relative_to(root)
        parts = set(rel.parts)
        if parts & SKIP_DIR_NAMES:
            continue
        if path.name == "__init__.py":
            continue
        yield path


def extract_surface(path: Path) -> list[tuple[str, str]]:
    """Return [(kind, name)] for public top-level classes and functions."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return []
    surface: list[tuple[str, str]] = []
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            surface.append((kind, node.name))
    surface.sort(key=lambda kv: (kv[0], kv[1]))
    return surface


def build_markdown() -> str:
    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/docs/generate_code_index.py — DO NOT EDIT -->")
    lines.append("<!-- last_reviewed: auto | owner: core | status: auto -->")
    lines.append("")
    lines.append("# Code Index (auto-generated)")
    lines.append("")
    lines.append("**Gateway** · **Wiki Home** · **References** · Code Index")
    lines.append("")
    lines.append(
        "Public top-level classes and functions exported by modules under "
        "`src/textgraphx/`. Regenerate with:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("python scripts/docs/generate_code_index.py")
    lines.append("```")
    lines.append("")
    lines.append("CI check: `python scripts/docs/generate_code_index.py --check`.")
    lines.append("")

    modules = list(iter_modules(PACKAGE_ROOT))
    for mod in modules:
        surface = extract_surface(mod)
        if not surface:
            continue
        rel = mod.relative_to(REPO_ROOT).as_posix()
        # link target is relative to docs/wiki/99-references/code-index.md (3 levels up)
        link_target = f"../../../{rel}"
        lines.append(f"## [{rel}]({link_target})")
        lines.append("")
        lines.append("| Kind | Name |")
        lines.append("| --- | --- |")
        for kind, name in surface:
            lines.append(f"| {kind} | `{name}` |")
        lines.append("")

    if not any(line.startswith("## ") for line in lines):
        lines.append("_No public symbols discovered._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if committed code-index.md is out of date.",
    )
    args = parser.parse_args()

    generated = build_markdown()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"error: {OUTPUT_PATH} is missing; run generator.", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if hashlib.sha256(current.encode()).digest() != hashlib.sha256(generated.encode()).digest():
            print(
                f"error: {OUTPUT_PATH} is stale; run "
                f"`python scripts/docs/generate_code_index.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
